export const INIT_MENU = "INIT_MENU";
export const INIT_MAIN_SECTION = "INIT_MAIN_SECTION";
export const OPEN_FILE = "OPEN_FILE";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
export const INIT_IMAGE = "INIT_IMAGE";
